name: composition

on: 
  workflow_dispatch:

jobs:
  create:
    name: Create files
    runs-on: ubuntu-latest
    steps:
      - name: create test
        uses: actions/create-test-files@9c7aed8037503d8b73180eba0eb6a420d43a414d
    
