name: composition

on: 
  workflow_dispatch:

jobs:
  create:
    name: Create files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: ls
      - name: create test
        uses: ./.github/actions/actions/create-files
    
