name: Deploy to Dropbox Test

on: 
  workflow_dispatch:
# [push, pull_request]

jobs:
  create:
    name: Create files
    runs-on: ubuntu-latest
    steps:
      - name: create world.txt
        run: mkdir test && echo hello > test/helloWorld1.txt && echo "hello 2" > test/helloWorld2.txt
        
      # Zip build
      - name: Zip files
        run: zip -r build.zip test
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: Build # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: build.zip
          # The desired behavior if no files are found using the provided path.
      

  deploy:
    name: Deploy to Dropbox 📦
    needs: create
    runs-on: ubuntu-latest
    outputs:
      link: ${{ steps.link-write.outputs.link }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: Build # optional
          # Destination path
          path: build # optional
          
      - name: ls
        run: cd build && ls
      
      # Deploy
      - name: Deploy to Dropbox
        # You may pin to the exact commit or the version.
        # uses: aTable/deploy-to-dropbox@d2a7533bc8aa47273469c24b137fc55e41760bca
        uses: aTable/deploy-to-dropbox@v1.0.7
        with:
          # Value should be a secret that is set in your repository settings
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          # Glob that you want to save to Dropbox e.g dir1/dir2/**/*.md or **/*.txt
          GLOB: build/*
          # The destination path prefix to save to in Dropbox. This will prepend the individual globs. Default value is "/"
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ github.ref_name }}-test/ # optional, default is /
          # Enable debugging.
          DEBUG: true # optional
          
      - name: Create Dropbox Link
        id: create-link-dropbox
        # You may pin to the exact commit or the version.
        # uses: RexIturan/create-link-dropbox@eb6698915884a1c95a804b482a6d8fcf6580d873
        uses: RexIturan/create-link-dropbox@v0.0.1-alpha
        with:
          # Value should be a secret that is set in your repository settings
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          # The path to the file to generate the link for. Default value is "/"
          DROPBOX_FILE_PATH: /${{ github.ref_name }}-test # optional, default is /
          # Enable debugging.
          DEBUG: false # optional
          
      - name: Write Link into Output
        id: link-write
        run: echo "link=${{ steps.create-link-dropbox.outputs.link }}" >> "$GITHUB_OUTPUT"
        
  publish-link:
    name: Share Link 🛎️
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      #Post Link to Discord
      - name: Discord Notify
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          # Title for card
          title: Build Link # optional, default is 
          # Content of card
          message: "Download Link: ${{needs.deploy.outputs.link}}" # default is 
          # If action is used in a pull request, attach the preview image for it to the card. Required for custom_image_url
          #include_image: # optional, default is false
          # Avatar to use for user
          #avatar_url: # optional, default is 
          # Username to send message as
          #username: # optional, default is GitHub
          # Colour for the edge of the card in hex
          #colour: # optional, default is #3371FF
          # Include custom image on card, include_image must be true
          #custom_image_url: # optional, default is 
          # Make the title of the card a link
          #title_url: # optional, default is 
