name: Deploy to Dropbox Test

on: 
  workflow_dispatch:
# [push, pull_request]

jobs:
  deploy:
    name: Deploy to Dropbox
    runs-on: ubuntu-latest
    steps:
      - name: create world.txt
        run: mkdir test && echo hello > test/helloWorld1.txt && echo "hello 2" > test/helloWorld2.txt
      
      # Checkout
      - name: Deploy to Dropbox
        # You may pin to the exact commit or the version.
        # uses: aTable/deploy-to-dropbox@d2a7533bc8aa47273469c24b137fc55e41760bca
        uses: aTable/deploy-to-dropbox@v1.0.7
        with:
          # Value should be a secret that is set in your repository settings
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          # Glob that you want to save to Dropbox e.g dir1/dir2/**/*.md or **/*.txt
          GLOB: ./test/*
          # The destination path prefix to save to in Dropbox. This will prepend the individual globs. Default value is "/"
          DROPBOX_DESTINATION_PATH_PREFIX: /${{ github.ref_name }}-test/ # optional, default is /
          # Enable debugging.
          DEBUG: true # optional
