name: Release Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release'
      
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
      - name: Use the obtained token
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"context":"test","state":"success"}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA?access_token=$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
    
      - uses: undergroundwires/bump-everywhere@master
        with:
          # Repository name with owner to bump & release. For example, undergroundwires/bump-everywhere
          # (Optional) Default: ${{ github.repository  }}
          # repository: ''

          # Name of the user who will do the bump commit
          # (Optional) Default: ${{ github.actor }}
          # user: ''

          # Commit message that will be used in the bump commit
          # (Optional) Default: ⬆️ bump everywhere to {{version}}
          # commit-message: ''

          # Personal access token (PAT) used to clone & push to the repository.
          # If you use default, it'll not trigger other actions, but your own PAT then it triggers new actions
          # (Optional) Default: ${{ github.token }}
          # git-token: ''

          # The type of the GitHub release
          # Options: 'release' | 'prerelease' | 'draft' | 'none' (does not release)
          # (Optional) Default: 'release'
          release-type: 'none'

          # Personal access token (PAT) used to release to GitHub.
          # Used only if release-type is not "none"
          # If you use default, it'll not trigger other actions, but your own PAT then it triggers new actions
          # (Optional) Default: ${{ github.token }}
          # release-token: ''

          # Git branch to push the changes such as version tags, CHANGELOG file, version changes...
          # Configuring this should not be needed for most use-cases.
          # Use this only if you DO NOT use a single main default branch (e.g. `master` or `main`).
          # (Optional) Default: Default "git clone" behavior. Checks out to default branch of remote.
          branch: 'release'
      - run: |
          echo The PR was merged
        
