name: Release Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release'
      
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create an incremental tag
        uses: aurestic/incremental-tag@1.0.8
        #with:
          # Flag indicating that the script should look for the lastest tag depending on the branch to which the merge is made. That is, if we are in the branch "8.0" and a merge of a PR is made, it will take the last tag "8.0.15.45" and not "11.0.56.23".
          #flag_branch: # optional
          # Message for the tag
          #message: # optional, default is Bump version
          # String to be added before the final tag, for example this parameter takes the value "v" the final tag will be "v8.0.15.45".
          #prev_tag: # optional, default is 
      - run: |
          echo The PR was merged
        
